const FETCH_DIRECTORIES = "FETCH_DIRECTORIES";
const FETCH_DIRECTORIES_BY_ID = "FETCH_DIRECTORIES_BY_ID";
const FETCH_SINGLE_DIRECTORY = "FETCH_SINGLE_DIRECTORY";

const REQUEST_DIRECTORIES_FAILD = "REQUEST_DIRECTORIES_FAILD";

const FILTER_DIRECTORIES_FOR_ITEM = "FILTER_DIRECTORIES_FOR_SELECT_ITEM";
const FILTER_DIRECTORIES_FOR_ROOT = "FILTER_DIRECTORIES_FOR_ROOT";

const CLEAR_SINGLE_DIRECORY = "CLEAR_SINGLE_DIRECORY";
const CLEAR_DIRECTORIES_TREE = "CLEAR_DIRECTORIES_TREE";

export {
  FETCH_DIRECTORIES,
  FETCH_DIRECTORIES_BY_ID,
  FETCH_SINGLE_DIRECTORY,
  REQUEST_DIRECTORIES_FAILD,
  FILTER_DIRECTORIES_FOR_ITEM,
  FILTER_DIRECTORIES_FOR_ROOT,
  CLEAR_SINGLE_DIRECORY,
  CLEAR_DIRECTORIES_TREE
};
