const INIT_DIRECTORIES = "INIT_DIRECTORIES";
const INIT_SINGLE_DIRECTORY = "INIT_SINGLE_DIRECTORY";
const INIT_CREATE_DIRECTORIES = "INIT_CREATE_DIRECTORIES";
const INIT_EDIT_DIRECTORY = "INIT_EDIT_DIRECTORY";
const INIT_REMOVE_DIRECTORY = "INIT_REMOVE_DIRECTORY";

const INIT_NOTICES = "INIT_NOTICES";
const INIT_SINGLE_NOTICE = "INIT_SINGLE_NOTICE";
const INIT_CREATE_NOTICES = "INIT_CREATE_NOTICES";
const INIT_EDIT_NOTICE = "INIT_EDIT_NOTICE";
const INIT_REMOVE_NOTICE = "INIT_REMOVE_NOTICE";
const INIT_REMOVE_NOTICES_FOR_DIRECTORY = "INIT_REMOVE_NOTICES_FOR_DIRECTORY";
const INIT_CHANGE_NOTICES_POSITION = "INIT_CHANGE_NOTICES_POSITION";

export {
  INIT_DIRECTORIES,
  INIT_CREATE_DIRECTORIES,
  INIT_SINGLE_DIRECTORY,
  INIT_EDIT_DIRECTORY,
  INIT_REMOVE_DIRECTORY,
  INIT_NOTICES,
  INIT_SINGLE_NOTICE,
  INIT_CREATE_NOTICES,
  INIT_EDIT_NOTICE,
  INIT_REMOVE_NOTICE,
  INIT_REMOVE_NOTICES_FOR_DIRECTORY,
  INIT_CHANGE_NOTICES_POSITION
};
