const FETCH_NOTICES = "FETCH_NOTICES";
const FETCH_SINGLE_NOTICE = "FETCH_SINGLE_NOTICE";

const FETCH_SUCCESS_CREATE_NOTICE = "FETCH_SUCCESS_CREATE_NOTICE";
const FETCH_SUCCESS_EDIT_NOTICE = "FETCH_SUCCESS_EDIT_NOTICE";
const FETCH_SUCCESS_REMOVE_NOTICE = "FETCH_SUCCESS_REMOVE_NOTICE";

const REQUEST_NOTICES_FAILD = "REQUEST_NOTICES_FAILD";

const REFRESH_NOTICES = "REFRESH_NOTICES";

const FILTER_NOTICES = "FILTER_NOTICES";

const CLEAR_SINGLE_NOTICE = "CLEAR_SINGLE_NOTICE";
const CLEAR_NOTICES_LIST = "CLEAR_NOTICES_LIST";

export {
  FETCH_NOTICES,
  FETCH_SINGLE_NOTICE,
  FETCH_SUCCESS_CREATE_NOTICE,
  FETCH_SUCCESS_EDIT_NOTICE,
  FETCH_SUCCESS_REMOVE_NOTICE,
  REQUEST_NOTICES_FAILD,
  REFRESH_NOTICES,
  FILTER_NOTICES,
  CLEAR_SINGLE_NOTICE,
  CLEAR_NOTICES_LIST
};
