const TOGGLE_SIDE_NAV_MENU = "TOGGLE_SIDE_NAV_MENU";
const GET_SIDE_NAV_MODAL_TYPE = "GET_SIDE_NAV_MODAL_TYPE";
const GET_SEARCH_TYPE = "GET_SEARCH_TYPE";

const OPEN_SIDE_NAV_MODAL = "OPEN_SIDE_NAV_MODAL";
const CLOSE_SIDE_NAV_MODAL = "CLOSE_SIDE_NAV_MODAL";

const OPEN_EDIN_MODAL = "OPEN_EDIN_MODAL";
const CLOSE_EDIT_MODAL = "CLOSE_EDIT_MODAL";

const OPEN_REMOVE_MODAL = "OPEN_REMOVE_MODAL";
const CLOSE_REMOVE_MODAL = "CLOSE_REMOVE_MODAL";

const CLOSE_ERROR_MODAL = "CLOSE_ERROR_MODAL";

export {
  TOGGLE_SIDE_NAV_MENU,
  GET_SIDE_NAV_MODAL_TYPE,
  GET_SEARCH_TYPE,
  OPEN_SIDE_NAV_MODAL,
  CLOSE_SIDE_NAV_MODAL,
  OPEN_EDIN_MODAL,
  CLOSE_EDIT_MODAL,
  OPEN_REMOVE_MODAL,
  CLOSE_REMOVE_MODAL,
  CLOSE_ERROR_MODAL
};
